<?php

/**
 * @file
 * Defines hooks used for JHU's iDC integration.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function idc_defaults_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if (isset($fields['field_member_of'])) {
    $fields['field_member_of']->addConstraint('WorkbenchAccess');
  }
  if (isset($fields['field_access_terms'])) {
    $fields['field_access_terms']->addConstraint('WorkbenchSections');
  }
}

/**
 * Implements hook_field_widget_info_alter().
 */
function idc_defaults_field_widget_info_alter(array &$info) {
  // Allow the idc_unique field to use the normal string_textfield widget as
  // opposed to defining its own empty extension of it.
  $info['string_textfield']['field_types'][] = 'idc_unique';
}
